version: '3'
services:
  linkding:
    build: .
    volumes:
      - static:/etc/linkding/static
      - /home/web/data/linkding:/etc/linkding/data
    ports:
      - 8001:8001
    command: bash bootstrap.sh
  server:
    build: server
    volumes:
      - /home/web/id:/etc/ssl/linkding
      - static:/usr/share/nginx/static
    ports:
      - 9000:8000
      - 9443:8443
    command: nginx -g "daemon off;"
volumes:
  static:
